version: '3.9'

services:
  decaf-backend:
    build:
      context: .         # Adjust if Dockerfile is in a subfolder
      dockerfile: Dockerfile
    container_name: decaf-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped